<?php 

/**
 * Joomla! 1.5 component courses
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_courses
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


  
// uncomment to add custom css file for this view,
// save the css file to media/com_courses/css/yourcss.css
//use media/com_courses folder to store your css,js,images,...

	//$document =& JFactory::getDocument();
    //$document->addStyleSheet($this->baseurl.'/media/com_courses/css/yourcss.css');
  ?>
<?php if ( $this->params->def( 'show_page_title', 1 ) ) : ?>
<h1 class="componentheading<?php echo $this->params->get( 'pageclass_sfx' ); ?> verde">
<?php echo $this->escape($this->params->get('page_title')); ?>
</h1>
<?php endif; ?>
<?php // DIV ITEM; ?>
<div class="itemDesc">
	<h3>Descrição</h3>
	<?php echo $this->item->description; ?>
	<?php if( $this->params->get('show_publish_up') && $this->item->publish_up ):?>
<h3>Publish_up</h3>
	<?php echo $this->item->publish_up; ?>
<?php endif; ?>


<?php if( $this->params->get('show_publish_down') && $this->item->publish_down ):?>
	<h3>Publish_down</h3>
	<?php echo $this->item->publish_down; ?>
<?php endif; ?>

<?php if (($this->params->get('show_author'))) : ?>
		<p class="small">
			<?php echo JText::_( 'Escrito por' ); ?>:<?php echo $this->item->created_by_alias; ?>
		</p>
<?php endif; ?>

<?php if ($this->params->get('show_create_date')) : ?>
		<p class="small">
		<?php echo JHTML::_('date', $this->item->created, JText::_('DATE_FORMAT_LC2')) ?>
		</p>
<?php endif; ?>

<?php if ( intval($this->item->modified) !=0 && $this->params->get('show_modify_date')) : ?>
	<p class="small">
	<?php echo JText::sprintf('LAST_UPDATED2', JHTML::_('date', $this->item->modified, JText::_('DATE_FORMAT_LC2'))); ?>
	</p>
<?php endif; ?>

<?php if ($this->params->get('show_hits')) : ?>
	<p class="small">
	<?php echo JText::_( 'Hits' ); ?>:<?php echo $this->item->hits; ?>
	</p>
<?php endif; ?>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" type="text/css" media="all" />
	<link rel="stylesheet" href="http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css" type="text/css" media="all" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
	<script src="http://jquery-ui.googlecode.com/svn/tags/latest/external/jquery.bgiframe-2.1.2.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/i18n/jquery-ui-i18n.min.js" type="text/javascript"></script>
<!--<h3 style="margin:10px 0 0 0"><?php //echo JText::_( 'Aulas' );?></h3>-->
	<div id="accordion">
	<?php $materia = null;?>
	<?php foreach($this->videos as $video): ?>
	<!--<li class="listaVideos"><a href="<?php //echo "index.php?option=com_courses&view=video&cid[]=".$video['id'];?>"><?php //echo $video['title'];?></a></li>-->
	<?php if ($video['materia'] == '') {
				$video['materia'] = $this->item->title;
			}
	?>
	<?php if($materia != $video['materia']): ?>
		<?php 
			if ($video['materia'] == '') {
				$video['materia'] = $this->item->title;
			}
			if ($video['materia'] != null) {
				printf($accordion_item, $item_links);
			}
		?>
		<?php $accordion_item = '<h3>&nbsp'.$video['materia'].'</h3><div><ul>%s</ul></div>';
				   $item_links = '<li  class="listaVideos"><a href="index.php?option=com_courses&view=video&cid[]='.$video['id'].'">'.$video['title'].'</a></li>';
		?>
		<?php $materia = $video['materia'];?>
	<?php else :?>
			<?php $item_links .= '<li  class="listaVideos"><a href="index.php?option=com_courses&view=video&cid[]='.$video['id'].'">'.$video['title'].'</a></li>';?>
	<?php endif; ?>
	<?php endforeach;?>
	<?php 
			if ($video['materia'] != null) {
				printf($accordion_item, $item_links);
			}
		?>
	</div>
</div>
<?php //DIV DESC; ?>
<div class="itemPreco">
<?php if (!$this->courseUserVideos) :?>
<h3>Investimento</h3>
	<p>
	  <spam>R$</spam>
	  <?php echo number_format($this->item->price, 2, '.', ''); ?>
	  <?php
	$StrItemid = '';
	$Itemid = JRequest::getVar('Itemid',null);
	if ($Itemid) {
		$StrItemid = '&Itemid='.$Itemid;
	}
	?>
</p>
<p>
	<button class="btCourses" onClick="location.href='index.php?option=com_courses&view=cart&task=cart&action=add&course=<?php echo $this->item->id.$StrItemid;?>'"><?php echo JText::_('Compre');?></button>
</p>
<?php else :?>
<?php 
		switch ($this->courseUserVideos[0]->status) {
			/* Aguardando Pagamento */
			case '1':
					//break;
			/* Em Análise */
			case '2':
					$msg = 'Aguardando confirmação do pagseguro';
					break;
			/* Paga */
			case '3':
					//break;
			/* Disponível */
			case '4':
					$msg = 'Este item já foi comprado e você já pode assistir os vídeos desta seção!';
					break;
			/* Em Disputa */
			case '5':
					//break;
			/* Devolvida */
			case '6':
					//break;
			/* Cancelada */
			case '7':
					$msg = 'Entre em contato com o administrador';
					break;
			default :
					break;
		}
?>
<h3>Investimento</h3>
<p><?php echo $msg;?></p>
<?php endif; ?>
</div>
<script>
	$(function() {
		$( "#accordion" ).accordion();
		$( "#accordion" ).accordion({
			icons: false
		});
	});
</script>
