<?php 

/**
 * Joomla! 1.5 component courses
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_courses
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


  
// uncomment to add custom css file for this view,
// save the css file to media/com_courses/css/yourcss.css
//use media/com_courses folder to store your css,js,images,...

	//$document =& JFactory::getDocument();
    //$document->addStyleSheet($this->baseurl.'/media/com_courses/css/yourcss.css');
?>
<div class="componentheading verde2">
	<?php echo $this->escape($this->params->get('page_title')); ?>
</div>
<?php 
	$video_id = JRequest::getVar( 'cid', null );
	if ($this->access && $video_id[0]!=63) :?>
<div>
	<h3>Ops!</h3>
	<?php 
				/*
				*	Código de erros
				*   Pagseguro
				*   1 : Aguardando pagamento
				*   2 : Em Análise
				*   3 : Paga
				*   4 : Disponível
				*   5 : Em disputa
				*   6 : Devolvida
				*   7 : Cancelada
				*   Master Juris
				*   8 : Área restrita
				*   9 : Número Máximo de visualizações excedido
				*   10: Período de visualizações expirado
				*   11: Video ou categoria indisponível (Despublicado)
				*/
	?>
	<?php switch($this->access):
		case 1:?>
		<p><?php echo JText::_('Aguardando pagamento.') ?></p>
		<?php break;?>
		<?php case 2:?>
		<p><?php echo JText::_('Pagamento em análise.') ?></p>
		<?php break;?>
		<?php case 5:?>
		<p><?php echo JText::_('Pagamento em disputa.') ?></p>
		<?php break;?>
		<?php case 6:?>
		<p><?php echo JText::_('Pagamento devolvido.') ?></p>
		<?php break;?>
		<?php case 7:?>
		<p><?php echo JText::_('Pedido cancelado.') ?></p>
		<?php break;?>
		<?php case 8:?>
		<p><?php echo JText::_('Área restrita.') ?></p>
		<?php break;?>
		<?php case 9:?>
		<p><?php echo JText::_('Número máximo de visualizações expirado.') ?></p>
		<?php break;?>
		<?php case 10:?>
		<p><?php echo JText::_('Período de visualização expirado.') ?></p>
		<?php break;?>
		<?php case 11:?>
		<p><?php echo JText::_('Vídeo ou categoria indisponível.') ?></p>
		<?php break;?>
	<?php endswitch;?>
</div>
<?php else : ?>
<!--<div id="dplayer">
<script src="<?php echo $this->baseurl.'/components/com_courses/assets/flowplayer-3.2.6.min.js';?>"></script>
<a 
	href="<?php echo $this->video[0]['url'];?>"  
	style="display:block;width:425px;height:300px;" 
	id="player">
</a>-->

<!--<script language="JavaScript">
	flowplayer("player", "<?php //echo $this->baseurl.'/components/com_courses/assets/'?>flowplayer-3.2.7.swf");
</script>-->
<div id="dplayer">
<!-- embed -->
<?php echo $this->video[0]['url'];?>
</div>
<div id="assistaAgora">
	<h3>Outras Aulas</h3>
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" type="text/css" media="all" />
	<link rel="stylesheet" href="http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css" type="text/css" media="all" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
	<script src="http://jquery-ui.googlecode.com/svn/tags/latest/external/jquery.bgiframe-2.1.2.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/i18n/jquery-ui-i18n.min.js" type="text/javascript"></script>
	<div id="accordion">
	<?php $materia = null;?>
	<?php foreach($this->videolist as $video): ?>
	<?php if ($this->video[0]['materia'] == '') {
				$this->video[0]['materia'] = 'Aulas';
			}
	?>
	<?php if($materia != $video->materia): ?>
		<?php 
			if ($video->materia != null) {
				printf($accordion_item, $item_links);
			}
		?>
		<?php $accordion_item = '<h3>&nbsp'.$video->materia.'</h3><div><ul>%s</ul></div>';
				   $item_links = '<li  class="videosListaVer"><a href="index.php?option=com_courses&view=video&cid[]='.$video->id.'">'.$video->title.'</a></li>';
		?>
		<?php $materia = $video->materia;?>
	<?php else :?>
			<?php $item_links .= '<li  class="videosListaVer"><a href="index.php?option=com_courses&view=video&cid[]='.$video->id.'">'.$video->title.'</a></li>';?>
	<?php endif; ?>
	<?php endforeach;?>
	<?php 
			if ($video->materia != null) {
				printf($accordion_item, $item_links);
			}
		?>
</div>
</div>
<?php endif;?>
<script>
	$(function() {
		$( "#accordion" ).accordion();
		$( "#accordion" ).accordion({
			icons: false
		});
	});
</script>