<?php 

/**
 * Joomla! 1.5 component courses
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_courses
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


jimport('joomla.application.component.view');
 /**
  * @package Courses
  */
  class CoursesViewVideo extends JView
  {
  		function display($tpl = null)
 	    {
  			global $mainframe;
 
			$pathway = &$mainframe->getPathway();
			$document = & JFactory::getDocument();
			$uri =& JFactory::getURI();
			$user =& JFactory::getUser();
  			$model = &$this->getModel();
  			$params = &$mainframe->getParams();
			$itemId = JRequest::getVar('Itemid', null);
			/*
				Se usuário estiver deslogado redireciona para o login
			*/
			//if ($user->id == 0) {
			/*
				if ($itemId) {
					$url = 'index.php?option=com_courses&view=video&layout=login&Itemid='.$itemId;
				} else {
					$url = 'index.php?option=com_courses&view=video&layout=login';
				}
				
				$mainframe->redirect( $url. $option, $msg );
				*/
			//}
			// Get the parameters of the active menu item
			$menus = &JSite::getMenu();
			$menu = $menus->getActive();
			$item =& $this->get('data');
			// fail if checked out not by 'me'
			  if ($model->isCheckedOut( $user->get('id') )) {
			  $msg = JText::sprintf( 'DESCBEINGEDITTED', JText::_( 'The list' ), $item->title );
			  $mainframe->redirect( 'index.php?option='. $option, $msg );
			  }
 			// Set the document page title
  			// because the application sets a default page title, we need to get it
  			// right from the menu item itself
  			if (is_object( $menu ) && isset($menu->query['view']) && $menu->query['view'] == 'item' && isset($menu->query['id']) && $menu->query['id'] == $item->id) {
  				$menu_params = new JParameter( $menu->params );
 		    	 if (!$menu_params->get( 'page_title')) {
 				 $params->set('page_title', $item->title);
  					}
  				} 
  				else 
  				{
  				$params->set('page_title', $item->title);
  				}
			$db = JFactory::getDBO();
			$query = "SELECT * "
			. " FROM #__videos"
			. " WHERE id = " . (int)$item->id
			. " LIMIT 1";
			$db->setQuery($query);
			$video = $db->loadAssocList();
			$access = $model->access();
			$videolist = $model->listVideos();
			/*
			*	Código de erros
			*   Pagseguro
			*   1 : Aguardando pagamento
			*   2 : Em Análise
			*   3 : Paga
			*   4 : Disponível
			*   5 : Em disputa
			*   6 : Devolvida
			*   7 : Cancelada
			*   Master Juris
			*   8 : Área restrita
			*   9 : Número Máximo de visualizações excedido
			*   10: Período de visualizações expirado
			*   11: Video ou categoria indisponível (Despublicado)
			*/
			//
			//if ($access) {
			//	switch ($access) {
			//		/* Aguardando Pagamento */
			//		case '1':
			//				$msg = JText::_('Aguardando pagamento');
			//				break;
					/* Em Análise */
			//		case '2':
			//				$msg = JText::_('Em análise');
			//				break;
					/* Paga */
			//		case '3':
			//				break;
					/* Disponível */
			//		case '4':
			//				break;
					/* Em Disputa */
			//		case '5':
			//				$msg = JText::_('Em disputa');
			//				break;
					/* Devolvida */
			//		case '6':
			//				$msg = JText::_('Devolvida');
			//				break;
					/* Cancelada */
			//		case '7':
			//				$msg = JText::_('Cancelado');
			//				break;
					/* Área Restrita */
			//		case '8':
			//				$msg = JText::_('Área restrita');
			//				break;
					/* Número máximo de visualizações */
			//		case '9':
			//				$msg = JText::_('Número máximo de visualizações expirado');
			//				break;
					/* Período de visualizações expirado */
			//		case '10':
			//				$msg = JText::_('Período de visualizações expirado');
			//				break;
			//		case '11':
			//				$msg = JText::_('Vídeo ou categoria indisponível');
			//				break;
			//		default :
			//				break;
			//	}
			//	$mainframe->enqueueMessage($msg);
			//} else {
			//		$model->hit();
			//}*/
			$document->setTitle( $params->get( 'page_title' ) );
			
 				//set breadcrumbs
 				if (isset( $menu ) && isset($menu->query['view']) && $menu->query['view'] != 'item'){
 				 $pathway->addItem($item->title, '');
 				 }
 				 
			 $this->assignRef('params', $params);
 			 $this->assignRef('item', $item);
			 $this->assignRef('video', $video);
			 $this->assignRef('access', $access);
			 $this->assignRef('videolist', $videolist);
  
  			 parent::display($tpl);
 		 }
  }