<?php 

/**
 * Joomla! 1.5 component courses
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_courses
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


jimport('joomla.application.component.view');
 /**
  * @package Courses
  */
  class CoursesViewCart extends JView
  {
  		function display($tpl = null)
 	    {
			global $mainframe;
 
			$pathway = &$mainframe->getPathway();
			$document = & JFactory::getDocument();
  			$model = &$this->getModel();
			$uri =& JFactory::getURI();
			$user =& JFactory::getUser();
  			//$model = &$this->getModel();
  			$params = &$mainframe->getParams();
			$session = JFactory::getSession();
			$cart = $session->get('cart', array(), 'course_cart');
			$courses = $model->getSelection($cart);
			$this->assignRef('courses', $courses);
			/* --
				Cria array para o PagSeguro
			*/
			$order = array();
			//$order[] = array('products' => array());
			foreach ($courses as $course) {
				$order['products'][] = array('id' => $course->id, 'title'=>$course->title, 'items'=>'1', 'price'=>$course->price );
			}
			$order['user'] = array(
						'id' => $user->id,
						'name' => $user->name,
						'email' => $user->email,
				);
			$this->assignRef('order', $order);
			//echo "<pre>";print_r($order);exit;
			//echo "<pre>";print_r($cart);print_r($model->getSelection($cart));exit;
			/*
  
			// Get the parameters of the active menu item
			$menus = &JSite::getMenu();
			$menu = $menus->getActive();
			$item =& $this->get('data');
			// fail if checked out not by 'me'
			  if ($model->isCheckedOut( $user->get('id') )) {
			  $msg = JText::sprintf( 'DESCBEINGEDITTED', JText::_( 'The list' ), $item->title );
			  $mainframe->redirect( 'index.php?option='. $option, $msg );
			  }
 			// Set the document page title
  			// because the application sets a default page title, we need to get it
  			// right from the menu item itself
  			if (is_object( $menu ) && isset($menu->query['view']) && $menu->query['view'] == 'item' && isset($menu->query['id']) && $menu->query['id'] == $item->id) {
  				$menu_params = new JParameter( $menu->params );
 		    	 if (!$menu_params->get( 'page_title')) {
 				 $params->set('page_title', $item->title);
  					}
  				} 
  				else 
  				{
  				$params->set('page_title', $item->title);
  				}
			$db = JFactory::getDBO();
			$query = "SELECT * "
			. " FROM #__videos"
			. " WHERE id = " . (int)$item->id
			. " LIMIT 1";
			$db->setQuery($query);
			$video = $db->loadAssocList();
			$access = $model->access();
			$model->hit();
			//print_r($access);exit;
			if ($access) {
				switch ($access) {
					case '1':
							$msg = 'Área Restrita';
							break;
					case '2':
							$msg = 'Número máximo de visualizações excedido';
							break;
					case '3':
							$msg = 'Período de visualizações esgotado';
							break;
					case '4':
							$msg = 'Este vídeo está temporariamente indisponível';
							break;
					case '5':
							$msg = 'Aguardando processamento de pagamento';
							break;
					default:
							break;
				}
				//$app =& JFactory::getApplication();
				//$app->redirect('index.php',$msg, 'alert');
				//$app->enqueueMessage("File was submitted successfully!");
				//$mainframe->redirect( 'index.php?option=com_courses&view=categories',$msg, 'message');
				$mainframe->enqueueMessage($msg);
			}
			$document->setTitle( $params->get( 'page_title' ) );
			
 				//set breadcrumbs
 				if (isset( $menu ) && isset($menu->query['view']) && $menu->query['view'] != 'item'){
 				 $pathway->addItem($item->title, '');
 				 }
 				 
			 $this->assignRef('params', $params);
 			 $this->assignRef('item', $item);
			 $this->assignRef('video', $video);
			 $this->assignRef('access', $access);
				*/
  			 parent::display($tpl);
 		 }
  }